replicaCount: 2

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: demo.local
  path: /
  pathType: Prefix
  tls:
    enabled: false
    secretName: demo-local-tls
