---
# Source: hello-world/templates/service.yaml
apiVersion: v1
kind: Service
app: hello-world

spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - port: 8180
      targetPort: 8180
      nodePort: 30080
  metadata:
  name: hello-hello-world
---
# Source: hello-world/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
app: hello-world

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: "hello-world:1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8180
